spring.application.name=pickados-api

#spring.webservices.path=/pickados-api/v1

spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=none

# JWT
jwt.secret=maybeWeNeverLearnTheFireAtTheGatesIsOurSavingGrace
jwt.expiration-ms=3600000


