server.port=8080

# ===============================
# = DATASOURCE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/pickados_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = MAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=tu_usuario_mailtrap
spring.mail.password=tu_password_mailtrap
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
